-- Logical relational schema for the portfolio project.
-- The executable SQLite database is generated by Python/src/ecom_opt/database.py.

CREATE TABLE dim_supplier (
    SupplierID TEXT PRIMARY KEY,
    SupplierName TEXT NOT NULL,
    Country TEXT NOT NULL,
    Region TEXT NOT NULL,
    StandardLeadTimeDays INTEGER NOT NULL,
    OnTimeDeliveryRate REAL NOT NULL,
    QualityAcceptanceRate REAL NOT NULL,
    OrderCostTRY REAL NOT NULL,
    PaymentTermsDays INTEGER NOT NULL
);

CREATE TABLE dim_product (
    SKU TEXT PRIMARY KEY,
    ProductName TEXT NOT NULL,
    Category TEXT NOT NULL,
    Segment TEXT NOT NULL,
    Collection TEXT NOT NULL,
    SupplierID TEXT NOT NULL,
    UnitCostTRY REAL NOT NULL,
    ListPriceTRY REAL NOT NULL,
    GrossMarginPct REAL NOT NULL,
    LeadTimeDays INTEGER NOT NULL,
    MOQ INTEGER NOT NULL,
    CasePack INTEGER NOT NULL,
    TargetServiceLevel REAL NOT NULL,
    BaseWeeklyDemand REAL NOT NULL,
    LaunchDate TEXT NOT NULL,
    LifecycleStage TEXT NOT NULL,
    FOREIGN KEY (SupplierID) REFERENCES dim_supplier (SupplierID)
);

CREATE TABLE fact_weekly_sales (
    WeekStart TEXT NOT NULL,
    SKU TEXT NOT NULL,
    Channel TEXT NOT NULL,
    CampaignName TEXT NOT NULL,
    PromotionFlag INTEGER NOT NULL,
    DiscountPct REAL NOT NULL,
    UnitsSold INTEGER NOT NULL,
    EstimatedDemandUnits REAL NOT NULL,
    LostSalesUnits REAL NOT NULL,
    GrossSalesTRY REAL NOT NULL,
    DiscountTRY REAL NOT NULL,
    NetRevenueTRY REAL NOT NULL,
    COGSTRY REAL NOT NULL,
    GrossProfitTRY REAL NOT NULL,
    AverageSellingPriceTRY REAL NOT NULL,
    StockoutFlag INTEGER NOT NULL,
    FOREIGN KEY (SKU) REFERENCES dim_product (SKU)
);

CREATE TABLE fact_inventory_snapshot (
    WeekStart TEXT NOT NULL,
    SKU TEXT NOT NULL,
    BeginningOnHand INTEGER NOT NULL,
    Receipts INTEGER NOT NULL,
    EstimatedDemandUnits INTEGER NOT NULL,
    UnitsSold INTEGER NOT NULL,
    LostSalesUnits INTEGER NOT NULL,
    EndingOnHand INTEGER NOT NULL,
    OnOrderUnits INTEGER NOT NULL,
    InventoryValueTRY REAL NOT NULL,
    WeeksOfSupply REAL NOT NULL,
    StockoutFlag INTEGER NOT NULL,
    ReorderPointReference INTEGER NOT NULL,
    ReorderTriggered INTEGER NOT NULL,
    FOREIGN KEY (SKU) REFERENCES dim_product (SKU)
);

